### ISSUE TITLE
Provide binaries

### ISSUE THREAD

**Issue by mruegenberg** [charlesveasey/vDome#11]
Hi,
it would be great to have binaries of vDome so that prospective users like me can easily test if it matches their needs...

thanks!

**Comment by thebelin** [comment]
Please provide working binaries. The build process does not work as outlined. Too many errors to list in Windows build process.

**Comment by charlesveasey** [comment]
I've provided Windows builds here:
http://charlesveasey.net/vdome/build/

v0.1) The version that matches the manual:
https://docs.google.com/document/d/1EHPpExjznFF6X0YTY5acLS0MNkEbtVFsLBCoJ2HHQlQ/edit#

v.0.2) The unfinished working version. Note the installation path cannot have any spaces.

Please note that this project is no longer active. The last thing I did before leaving my position at the IAIA Digital Dome was to switch the dome to this actively developed software:
https://github.com/paperManu/splash
