### ISSUE TITLE
How to use vDome

### ISSUE THREAD

**Issue by ZijingMao** [charlesveasey/vDome#13]
I'm completely new to dome projection but our lab in UTSA is about to construct a dome for immersive experiment purpose. When I saw this work I think this is fantastic, exactly what we want.

After I follow the instruction to compile vDome, I got a black window of 720 by 2048. So I wonder is there any tutorial that I can follow.

Thank you very much!
Zijing

**Comment by charlesveasey** [comment]
I've provided Windows builds here:
http://charlesveasey.net/vdome/build/

v0.1) The version that matches the manual:
https://docs.google.com/document/d/1EHPpExjznFF6X0YTY5acLS0MNkEbtVFsLBCoJ2HHQlQ/edit#

v.0.2) The unfinished working version. Note the installation path on this cannot have any spaces.

Please note that this project is no longer active. The last thing I did before leaving my position at the IAIA Digital Dome was to switch the dome to this actively developed software:
https://github.com/paperManu/splash
