### ISSUE TITLE
Having trouble displaying any media or alignment grid

### ISSUE THREAD

**Issue by Heather-Stuart** [charlesveasey/vDome#14]
Hi there!

I have successfully compiled vDome, but can't seem to get it to work properly. I have put in the proper data regarding my projectors and control monitor in the settings.xml file, and at first glance, things seem to work just fine. I can get the menu to come up on my projectors, however it does not display an alignment grid, and I cannot get any media to display, regardless of what I put in the the settings file (although the displayed framerate will change based on the input I am trying). I am able to access the Warp -> Bezier Grid and Cornerpin, which is literally the only imagery I am able to get vDome to display. My ultimate goal is to use vDome with Spout, but I can't even begin to setup my dome alignment. 

Any help you can provide would make me very grateful!!

Thanks! 

- Heather

**Comment by charlesveasey** [comment]
I've provided Windows builds here:
http://charlesveasey.net/vdome/build/

v0.1) The version that matches the manual:
https://docs.google.com/document/d/1EHPpExjznFF6X0YTY5acLS0MNkEbtVFsLBCoJ2HHQlQ/edit#

v.0.2) The unfinished working version. Note the installation path on this cannot have any spaces.

Please note that this project is no longer active. The last thing I did before leaving my position at the IAIA was to switch the dome to this actively developed software:
https://github.com/paperManu/splash
