### ISSUE TITLE
Can't get vdome compiled on windows7

### ISSUE THREAD

**Issue by dbassix** [charlesveasey/vDome#3]
While compiling vdome i allways get errors with spout namespace not available in spoutR.h

System:
Windows7 64Bit Prof
Visual Studio 2012 Express

**Comment by charlesveasey** [comment]
you must add the spout dll file to the bin.

**Comment by dbassix** [comment]
I did add the spout32.dll into my bin dir, but even the include "Spout.h" is underlined, so there might be something missing?!

**Comment by mogmarsh** [comment]
I am having the same problem. I have tried multiple versions of Spout32.dll and have also tried including the Spout 2.0.002 SDK code directly. Has anyone found a fix for this?

**Comment by charlesveasey** [comment]
I haven't compiled since spout v2.0. It seems they have changed some things  since version v1.x. I'm away from the office for a few months, so I'd suggest to either fork and fix the spout related errors or to compiled with Spout v1. Also I have compiled versions Of vDome for windows if you need them.

**Comment by mogmarsh** [comment]
I actually got it to work by installing https://github.com/Mat-Loz/ofxSpout, adding the addon files to the project, and then adding the paths for the addon to the 3 different appropriate locations in VisualStudio. Thanks for the reply. We're excited to use it!

**Comment by SeanJD** [comment]
Hi Charles. I'm also having this problem and having a load of link errors when trying to update using the ofxSpout addon. Probably doing something obvious but quite new to VS and dependencies etc. If you have a compiled version of vDome for Windows that I could trial it would make me happy... :)

**Comment by charlesveasey** [comment]
Spout has been updated to v2.0. Closing an old ticket.
