### ISSUE TITLE
Compile problem with linux 64bit

### ISSUE THREAD

**Issue by Giladx** [charlesveasey/vDome#4]
Hello 

compiling with codeblocks of0.8.4 and I am getting this errors
`src/vdome/input/media/media.cpp|242|error: ‘class vd::VideoLinux’ has no member named ‘getWidth’|`
`src/vdome/input/media/media.cpp|249|error: ‘class vd::VideoLinux’ has no member named ‘getHeight’|`

thanks for any replay

**Comment by charlesveasey** [comment]
Hi,

I don't have a linux machine with me, but it seems like an easy fix. I've updated the repo to include the method definitions.
