### ISSUE TITLE
hap problem

### ISSUE THREAD

**Issue by leolodreamland** [charlesveasey/vDome#5]
trying to build on yosemite but getting: error Hap QuickTime support requires 32-bit QuickTime APIs but this target is 64-bit

**Comment by charlesveasey** [comment]
This isn't a vDome issue exactly. The openFramework version Hap requires QuickTime which is a 32bit library. If you compile openFrameworks as 64bit then it will automatically switch to the newer AVFoundation library. There is already an issue over at the ofxHapPlayer repo:

https://github.com/bangnoise/ofxHapPlayer/issues/7

You can compile as 32 bit or you can compile as 64 bit (removing first HAP from source code) and use Syphon to feed in a Hap video.
