### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by GoDJr** [charlesveasey/vDome#6]
Hi Charles, 

I am currently trying to compile Vdome on Yosemite and i keep running into different issues. First it was the hap issue so i followed what you said in the other issues by removing hap in the code. now i keep getting an error that says ofConstants.H file not found and another error that says ofMain.H not found.  I am using Xcode 6.4 and OF 0.8.4. I really have no idea how to code and so i am just lost. Is there anyway i could get a prebuilt file or a detailed tutorial?

**Comment by charlesveasey** [comment]
Closing an old ticket
