### ISSUE TITLE
Wont Compile on OSX

### ISSUE THREAD

**Issue by TheSinding** [charlesveasey/vDome#8]
Hi, i have a problem compiling on OSX.

ofxMultiGLFWWindow, cant compile for some reason, with vdome debug nor vdome release.
It gets alot of errors.

If I build it with openframeworks, it compiles, but nothing happens.

I´m using the newest xcode v7.1.
OSX v10.11.2

Error codes:
    /Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:113:8: Virtual function 'getWindowMode' has a different return type ('int') than the function it overrides (which has return type 'ofWindowMode')

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:328:2: Use of undeclared identifier 'ofNotifySetup'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:330:9: Use of undeclared identifier 'ofNotifyUpdate'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:353:52: Use of undeclared identifier 'ofGetGLProgrammableRenderer'; did you mean 'ofIsGLProgrammableRenderer'?

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:353:41: No viable conversion from 'bool' to 'ofPtr<ofGLProgrammableRenderer>' (aka 'std::__1::shared_ptr<ofGLProgrammableRenderer>')

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:360:25: Use of undeclared identifier 'ofBgColorPtr'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:382:13: Use of undeclared identifier 'ofNotifyDraw'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1048:3: Use of undeclared identifier 'ofNotifyMousePressed'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1051:3: Use of undeclared identifier 'ofNotifyMouseReleased'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1066:3: Use of undeclared identifier 'ofNotifyMouseMoved'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1068:3: Use of undeclared identifier 'ofNotifyMouseDragged'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1086:2: Use of undeclared identifier 'ofNotifyDragEvent'; did you mean 'ofNotifyEvent'?

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1086:20: Non-const lvalue reference to type 'ofEvent<void>' cannot bind to a value of unrelated type 'ofDragInfo'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1211:3: Use of undeclared identifier 'ofNotifyKeyPressed'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1213:3: Use of undeclared identifier 'ofNotifyKeyReleased'

/Users/kennethdanielsen/Downloads/of_v0.9.0_osx_release/addons/ofxMultiGLFWWindow/src/ofxMultiGLFWWindow.cpp:1223:2: Use of undeclared identifier 'ofNotifyWindowResized'

**Comment by charlesveasey** [comment]
ofxMultiGLFWWindow is no longer necessary in of-0.9.0. I've updated the readme to show which addons are now needed.
