### ISSUE TITLE
Exception thrown at 0x005EDEEA in vDome_debug.exe: 0xC0000005: Access violation reading location 0x00000048.

### ISSUE THREAD

**Issue by uzarsalan** [charlesveasey/vDome#9]
Hi! Yes, this problem is continues. Visual Studio Community 2015 gave me error:

"Exception thrown at 0x005EDEEA in vDome_debug.exe: 0xC0000005: Access violation reading location 0x00000048.

If there is a handler for this exception, the program may be safely continued."

It stops on

void ofAppGLFWWindow::hideCursor(){
glfwSetInputMode(windowP,GLFW_CURSOR,GLFW_CURSOR_HIDDEN);
};

in file \libs\openFrameworks\app\ofAppGLFWWindow.cpp

Please help me!

Windows 10

**Comment by charlesveasey** [comment]
I've tested and is ok. Maybe you included ofxMultiGLFWWindow, which is no longer necessary with of-0.9.0. I've updated the readme to reflect which addons to use in of-0.9.0.

Note: A quick test against the oF 0.9.1 doesn't work, use 0.9.0.

Also: I've working on a bit of a refactor right now, which is mostly done. This will not be compatible with older versions. If you want to check that out instead. It's under the warp-addon branch of vDome. 

Lastly, don't forget about the player interface. 
https://github.com/charlesveasey/vDome-player
